"""Deterministic rule engine — runs BEFORE the LLM.

This is the heart of GxP-Struct. The promise of the design is that for
classification and timeline questions, the answer is *not* generated by
an LLM at all — it is computed by this module from the SOP's hard rules.
The LLM is only invoked for open-ended questions where no rule applies.

Every rule that fires returns a `RuleResult` with an explicit citation
back to the SOP section it came from. Citations are non-negotiable: if a
rule cannot cite a section, it does not fire.

Rule sources (Deviation SOP Rev 1.0, effective 2026-04-25):
    - 5.1  Initiation clock = 2 business days; English-only except Austria.
    - 5.2  Default = Level 1 if not in Attachment 4.
    - 5.2  L2 triggers: critical process parameters, sterility compromises,
           falsified data — always Level 2.
    - 5.2  Close Reference Deviations are always Level 1.
    - 5.2  Quality Management may override L1 -> L2.
    - 5.3  Performance timelines table.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class Intent(str, Enum):
    CLASSIFICATION = "classification"
    TIMELINE = "timeline"
    INITIATION = "initiation"
    LANGUAGE = "language"
    RESPONSIBILITY = "responsibility"
    GENERAL = "general"


@dataclass
class Citation:
    sop_section: str
    sop_section_title: str
    sop_version: str = "1.0"
    sop_effective_date: str = "2026-04-25"
    quote: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "sop_section": self.sop_section,
            "sop_section_title": self.sop_section_title,
            "sop_version": self.sop_version,
            "sop_effective_date": self.sop_effective_date,
            "quote": self.quote,
        }


@dataclass
class RuleResult:
    fired: bool
    intent: Intent
    rule_id: str
    answer: str
    citations: list[Citation] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def miss(cls, intent: Intent) -> "RuleResult":
        return cls(fired=False, intent=intent, rule_id="", answer="")


# ---------------------------------------------------------------------------
# Configurable lookup tables
# ---------------------------------------------------------------------------

ATTACHMENT_4_REFERENCE_LIST: set[str] = set()  # populate from controlled CSV

L2_TRIGGER_PATTERNS: list[tuple[str, str]] = [
    (r"\bcritical process parameter", "critical process parameters"),
    (r"\bcpp\b", "critical process parameters"),
    (r"\bsterility\b", "sterility compromise"),
    (r"\bsterile\b", "sterility compromise"),
    (r"\bfalsif", "falsified data"),
    (r"\bdata integrity\b", "falsified data"),
]

LANGUAGE_EXEMPTIONS: set[str] = {"austria"}
INITIATION_CLOCK_BUSINESS_DAYS = 2

TIMELINE_TABLE: dict[str, str] = {
    "level 1 completion": "30 calendar days from initiation",
    "level 2 investigation": "60 calendar days from initiation",
    "capa execution": "60 calendar days from investigation approval",
}

RESPONSIBILITY_TABLE: dict[str, str] = {
    "originator": "Evaluation and initiation of the record in GEMS within 2 business days.",
    "deviation owner": "Accountable for containment, impact assessment, and risk-based leveling.",
    "quality approver": "Sole authority for final leveling approval and disposition oversight.",
}


# ---------------------------------------------------------------------------
# Intent detection — TIMELINE before CLASSIFICATION (deadline > level routing)
# ---------------------------------------------------------------------------

_INTENT_PATTERNS: list[tuple[Intent, list[str]]] = [
    (Intent.TIMELINE, [
        r"\bdeadline", r"\bhow many days", r"\bcalendar days\b",
        r"\bcompletion\b", r"\binvestigation deadline\b",
        r"\bcapa\s+(?:deadline|execution|due)\b", r"\bdue (?:in|by|date)\b",
    ]),
    (Intent.CLASSIFICATION, [
        r"\blevel\s*[12]\b", r"\bclassif", r"\bdefault\b", r"\battachment\s*4\b",
        r"\bwhat level\b", r"\bl[12]\b", r"\breclassif",
    ]),
    (Intent.INITIATION, [
        r"\binitiat", r"\bclock[- ]?start", r"\b2 business days\b",
        r"\bopen the record\b", r"\bdiscovery\b",
    ]),
    (Intent.LANGUAGE, [
        r"\blanguage\b", r"\bin english\b", r"\baustria\b", r"\bbiolife\b", r"\bexempt",
    ]),
    (Intent.RESPONSIBILITY, [
        r"\boriginator\b", r"\bdeviation owner\b", r"\bquality approver\b",
        r"\bwho (?:is|owns|approves)\b", r"\bresponsib",
    ]),
]


def detect_intent(query: str) -> Intent:
    q = query.lower()
    for intent, patterns in _INTENT_PATTERNS:
        if any(re.search(p, q) for p in patterns):
            return intent
    return Intent.GENERAL


# ---------------------------------------------------------------------------
# Rule implementations
# ---------------------------------------------------------------------------

def _check_l2_triggers(query: str) -> str | None:
    q = query.lower()
    for pat, label in L2_TRIGGER_PATTERNS:
        if re.search(pat, q):
            return label
    return None


def _is_in_attachment_4(query: str) -> bool:
    if not ATTACHMENT_4_REFERENCE_LIST:
        return False
    q = query.lower()
    return any(item.lower() in q for item in ATTACHMENT_4_REFERENCE_LIST)


def classify_deviation(query: str) -> RuleResult:
    trigger = _check_l2_triggers(query)
    if trigger:
        return RuleResult(
            fired=True,
            intent=Intent.CLASSIFICATION,
            rule_id="R-5.2-L2_TRIGGER",
            answer=(
                f"Level 2 (mandatory). Per SOP \u00a7 5.2, deviations involving "
                f"{trigger} are always Level 2 regardless of frequency."
            ),
            citations=[Citation(
                sop_section="5.2",
                sop_section_title="Risk-Based Leveling",
                quote=("Deviations involving critical process parameters, "
                       "sterility compromises, or falsified data are always Level 2."),
            )],
            metadata={"level": "L2", "trigger": trigger, "deterministic": True},
        )

    if not _is_in_attachment_4(query):
        return RuleResult(
            fired=True,
            intent=Intent.CLASSIFICATION,
            rule_id="R-5.2-DEFAULT_L1",
            answer=(
                "Level 1 (default). Per SOP \u00a7 5.2, if a deviation is not listed "
                "in Attachment 4 (Investigation \u2013 CAPA Reference List), it is "
                "classified as Level 1 by default. Quality Management may "
                "re-classify to Level 2 based on evaluation."
            ),
            citations=[Citation(
                sop_section="5.2",
                sop_section_title="Risk-Based Leveling",
                quote="If an issue is not listed in Attachment 4, it is a Level 1 by default.",
            )],
            metadata={"level": "L1", "deterministic": True,
                      "override_path": "Quality Management"},
        )
    return RuleResult.miss(Intent.CLASSIFICATION)


def get_timeline(query: str) -> RuleResult:
    q = query.lower()
    for event, deadline in TIMELINE_TABLE.items():
        if event in q:
            return RuleResult(
                fired=True,
                intent=Intent.TIMELINE,
                rule_id=f"R-5.3-{event.replace(' ', '_').upper()}",
                answer=f"{event.title()}: {deadline} (per SOP \u00a7 5.3).",
                citations=[Citation(
                    sop_section="5.3",
                    sop_section_title="Performance Timelines",
                    quote=f"{event.title()}: {deadline}",
                )],
                metadata={"event": event, "deadline": deadline, "deterministic": True},
            )
    return RuleResult.miss(Intent.TIMELINE)


def get_initiation_rule(query: str) -> RuleResult:
    return RuleResult(
        fired=True,
        intent=Intent.INITIATION,
        rule_id="R-5.1-CLOCK_START",
        answer=(
            f"The record must be initiated within "
            f"{INITIATION_CLOCK_BUSINESS_DAYS} business days of discovery, with "
            f"impacted lot numbers populated (SOP \u00a7 5.1)."
        ),
        citations=[Citation(
            sop_section="5.1",
            sop_section_title="Initiation and Containment",
            quote=(f"Initiate within {INITIATION_CLOCK_BUSINESS_DAYS} business days "
                   "of discovery and populate impacted lot numbers."),
        )],
        metadata={"initiation_clock_business_days": INITIATION_CLOCK_BUSINESS_DAYS,
                  "deterministic": True},
    )


def get_language_rule(query: str) -> RuleResult:
    q = query.lower()
    mentioned = next((c for c in LANGUAGE_EXEMPTIONS if c in q), None)
    if mentioned:
        return RuleResult(
            fired=True,
            intent=Intent.LANGUAGE,
            rule_id="R-5.1-LANG_EXEMPTION",
            answer=(
                f"Records at the {mentioned.title()} BioLife centers are exempt "
                "from the English-only requirement (SOP \u00a7 5.1). All other sites "
                "must record in English."
            ),
            citations=[Citation(
                sop_section="5.1",
                sop_section_title="Initiation and Containment",
                quote="All records must be in English (Exemption: Austria BioLife centers).",
            )],
            metadata={"exempt_country": mentioned, "default_language": "English",
                      "deterministic": True},
        )
    return RuleResult(
        fired=True,
        intent=Intent.LANGUAGE,
        rule_id="R-5.1-LANG_DEFAULT",
        answer=("All records must be in English. The only exemption is Austria "
                "BioLife centers (SOP \u00a7 5.1)."),
        citations=[Citation(
            sop_section="5.1",
            sop_section_title="Initiation and Containment",
            quote="All records must be in English (Exemption: Austria BioLife centers).",
        )],
        metadata={"default_language": "English",
                  "exemptions": list(LANGUAGE_EXEMPTIONS),
                  "deterministic": True},
    )


def get_responsibility(query: str) -> RuleResult:
    q = query.lower()
    for role, resp in RESPONSIBILITY_TABLE.items():
        if role in q:
            return RuleResult(
                fired=True,
                intent=Intent.RESPONSIBILITY,
                rule_id=f"R-3.0-{role.replace(' ', '_').upper()}",
                answer=f"{role.title()}: {resp} (per SOP \u00a7 3.0).",
                citations=[Citation(
                    sop_section="3.0",
                    sop_section_title="Responsibilities",
                    quote=f"{role.title()}: {resp}",
                )],
                metadata={"role": role, "deterministic": True},
            )
    return RuleResult.miss(Intent.RESPONSIBILITY)


# ---------------------------------------------------------------------------
# Top-level dispatch
# ---------------------------------------------------------------------------

def evaluate(query: str) -> RuleResult:
    intent = detect_intent(query)
    if intent == Intent.TIMELINE:
        return get_timeline(query)
    if intent == Intent.CLASSIFICATION:
        return classify_deviation(query)
    if intent == Intent.INITIATION:
        return get_initiation_rule(query)
    if intent == Intent.LANGUAGE:
        return get_language_rule(query)
    if intent == Intent.RESPONSIBILITY:
        return get_responsibility(query)
    return RuleResult.miss(Intent.GENERAL)
